### ISSUE TITLE
PyPI release?

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.lifecycleevent#12]
Could we get a PyPI release when convenient please? 

There really aren't many major changes except for the claimed and tested support of specific Python versions, which has been indicated to be a sufficient condition. It would also be nice for the new documentation link get published. pypi.python.org has dropped the ability to edit existing releases (even though the form is still there, it doesn't work) and pypi.org doesn't yet have that functionality, so the only way to accomplish this is with a new release.

I'd be happy to make the release if I had access.

**Comment by mgedmin** [comment]
You have PyPI rights now.

**Comment by jamadden** [comment]
Thank you! 4.2.0 has been pushed to PyPI.
